on:
  - push
  - delete

jobs:
  widoco:
    runs-on: ubuntu-latest
    name: A conversion of ttl to html
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: soilwise-he/soil-health-knowledge-graph
          fetch-depth: 2
          path: '.'
      - run: git checkout HEAD^
      - run: ls .
      - run: ls ./soil-health-knowledge-graph
      - name: widoco
        id: widoco
        uses: soilwise-he/widoco-action@v0.2
        with:
          file-input: ../../github/workspace/soil_health_KG.ttl
          options: -excludeProvenance -getOntologyMetadata
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: pages
      - name: Copy files
        run: |
          cp -R ./out ./pages
      - name: Commit files
        run: |
          cd pages
          git config --local user.email "noreply@lsc-hubs.org"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -a -m "Add converted"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  
          directory: pages
