on:
  - push
  - delete

jobs:
  widoco:
    runs-on: ubuntu-latest
    name: A conversion of ttl to html
    container:
      image: ghcr.io/dgarijo/widoco:v1.4.25
    steps:
      - run: mkdir /usr/local/widoco/out 
      - run: wget https://github.com/soilwise-he/soil-health-knowledge-graph/raw/refs/heads/main/soil_health_KG.ttl -o ./kg.ttl 
      - run: java -jar /usr/local/widoco/widoco.jar -ontFile ./kg.ttl -outFolder /usr/local/widoco/out -rewriteAll -uniteSections -excludeProvenance -getOntologyMetadata
      - run: ls /usr/local/widoco/out
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: pages
      - name: Copy files
        run: |
          cp -R  /usr/local/widoco/out ./pages
      - name: Commit files
        run: |
          cd pages
          git config --local user.email "noreply@lsc-hubs.org"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -a -m "Add converted"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  
          directory: pages
